#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.
# But the main domain still shows Hello world

apt-get update -y && apt-get upgrade -y
apt-get install nginx -y
chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
line="\\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "48i $line" /etc/nginx/sites-available/default
service nginx restart
