#!/usr/bin/env bash

pkill -f apache
chmod 644 /etc/nginx/nginxconf
sed -i "1i user nginx;" /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
